name: CI ビルド

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - line-manager
      - dev
      - neo
    tags:
      - 'v*'
  merge_group:

permissions:
  contents: write

jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: '%compiler% -dumpmachine; %compiler% -dumpversion'
      CCACHE_NOHASHDIR: 'true'
      CCACHE_HARDLINK: 'true'
      CCACHE_BASEDIR: '${{ github.workspace }}'

    steps:
    - name: コードのチェックアウト
      uses: actions/checkout@v5
      with:
        ref: ${{ github.sha }}
        submodules: 'recursive'
        fetch-depth: 0

    - name: キャッシュの設定
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: 必要に応じて署名キーを書き込む
      if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.event_name != 'pull_request'
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
        fi

    - name: Java の設定
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Gradle の設定
      uses: gradle/actions/setup-gradle@v5

    - name: Android SDK の設定
      uses: android-actions/setup-android@v3

    - name: ninja の設定
      uses: seanmiddleditch/gha-setup-ninja@master
      with:
        version: 1.12.1

    - name: CMake の設定
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.1.1'

    - name: Android 付属の cmake を削除
      shell: bash
      run: rm -rf "$ANDROID_HOME/cmake"

    - name: gradlew に実行権限を付与
      run: chmod +x gradlew

    - name: commit id の設定
      run: echo "commit=$(echo ${{ github.sha }} | cut -c-7)" > $GITHUB_ENV

    - name: Gradle でビルド
      run: ./gradlew buildAll

    - name: Release アーティファクトのアップロード
      uses: actions/upload-artifact@v5
      with:
        name: npatch-release-${{ env.commit }}
        path: out/release/*
        retention-days: 14

    - name: Debug アーティファクトのアップロード
      uses: actions/upload-artifact@v5
      with:
        name: npatch-debug-${{ env.commit }}
        path: out/debug/*
        retention-days: 7

    - name: mappings のアップロード
      uses: actions/upload-artifact@v5
      with:
        name: mappings-${{ env.commit }}
        path: |
          patch-loader/build/outputs/mapping
          manager/build/outputs/mapping

    - name: symbols のアップロード
      uses: actions/upload-artifact@v5
      with:
        name: symbols-${{ env.commit }}
        path: |
          patch-loader/build/symbols

    - name: GitHub リリースの作成（タグプッシュ時のみ）
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          out/release/*
          out/debug/*
        generate_release_notes: true
        fail_on_unmatched_files: false